<?php 

$title = $this->translate('PPHulk');

$this->headTitle()->append($title);  

$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć daną regułę ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a").tooltip() });'
);

$nr = ($this->rules->getCurrentPageNumber()-1) * $this->rules->getItemCountPerPage();
?>
<?php echo $this->render('confirm.phtml') ?>
<fieldset class="table_container">
    <legend>
        <?php echo $title ?>
        <span id="options_container">
            <a href="#" id="b_options_container"><i class="icon-caret-right"></i> <?php echo $this->translate('Opcje') ?></a>
        </span>
    </legend>
    <?php echo $this->render('paginator_options.phtml') ?>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th>#</th>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php 
                $params = array(
                    'items' => $this->options['items'],
                    'order' => $order,
                    'desc' => (int)$this->options['desc'],
                    'page' => $this->options['page']
                );
            
                if($this->options['order'] == $order) {
                    $params['desc'] = (int)(!$this->options['desc']);
                }
                $url = $this->urlGetParams(null, $params);
            ?>
            <th>
                <a href="<?php echo $url; ?>">
                    <?php echo $this->translate('order_' . $order) ?> <?php if($order == $this->options['order']):?><i class="<?php if($this->options['desc']): ?>icon-caret-down<?php else: ?>icon-caret-up<?php endif; ?>"></i><?php endif; ?>
                </a>
            </th>
            <?php endforeach; ?>
            <th></th>
        </tr>
        <?php if(count($this->rules) == 0): ?>
        <tr>
            <td colspan="<?php echo count($this->options['orders']) + 2 ?>" class="table-nothing"><?php echo $this->translate('Nie zdefiniowano reguł') ?></td>
        </tr>
        <?php else: ?>
        <?php foreach($this->rules as $rule): ?>
        <tr>
            <td class="table_nr"><?php echo ++$nr ?></td>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php if($order == 'rule_priority'): ?>
            <td><?php echo $rule->getPriority() ?></td>
            <?php elseif($order == 'rule_ip'): ?>
            <td><?php echo $rule->getIp() ?></td>
            <?php elseif($order == 'resgroup_name'): ?>
            <?php 
            $resgroup = $rule->getAclResgroup();
            if($resgroup != null) {
                $resgroupName = $resgroup->getName();
            } else {
                $resgroupName = '-';
            }
            ?>
            <td><?php echo $resgroupName ?></td>            
            <?php elseif($order == 'rule_dateCreated'): ?>
            <td><?php echo $rule->getDateCreated()->toString('dd.MM.YYYY HH:mm') ?></td>
            <?php elseif($order == 'rule_dateExpired'): ?>
            <?php 
                $date = $rule->getDateExpired();
                if($date == null) {
                    $dateExpired = '-';
                } else {	
                    $dateExpired = $date->toString('dd.MM.YYYY HH:mm');
                }
            ?>
            <td><?php echo $dateExpired ?></td>
            <?php endif ?>
            <?php endforeach ?>
            <td class="table-options">
                <a href="<?php echo $this->baseUrl('/blocker/edit/id/' . $rule->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->baseUrl('/blocker/delete/id/' . $rule->getId()) ?>" class="btn btn-confirm btn-danger btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Usuń') ?>"><i class="icon-trash icon-white"></i></a>
            </td>
        </tr>
        <tr>
            <td class="blocker-message-title"><?php echo $this->translate('Powód:') ?></td>
            <?php $msg = $rule->getMessage() ?>
            <td colspan="<?php echo count($this->options['orders']) + 2 ?>" class="blocker-message"><?php if(empty($msg)): ?>-<?php else: ?>&bdquo;<?php echo $msg ?>&rdquo;<?php endif ?></td>
        </tr>
        <?php endforeach; ?>
        <?php endif ?>
    </table>
    <?php echo $this->paginationControl($this->rules,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => array(
                                        'items' => $this->items,
                                        'order' => $this->order,
                                        'desc' => (int)($this->desc)
                                    )
                                )); ?>
</fieldset>