<?php 

$title = $this->translate('Lista dystrybutorów');
$this->headTitle()->append($title);      

$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć tego dystrybutora ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a").tooltip() });'
);

$nr = ($this->distributors->getCurrentPageNumber()-1) * $this->distributors->getItemCountPerPage();

$this->isEnablePaginatorOrders = false;
$this->isEnablePaginatorOrder = false;

?>
<?php echo $this->render('confirm.phtml') ?>
<fieldset class="table_container">
    <legend>
        <?php echo $title ?>
        <span id="options_container">
            <a href="#" id="b_options_container"><i class="icon-caret-right"></i> <?php echo $this->translate('Opcje') ?></a>
        </span>
    </legend>
    <?php echo $this->render('paginator_options.phtml') ?>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th><?php echo $this->translate('Nr') ?></th>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php 
                $params = array(
                    'items' => $this->options['items'],
                    'order' => $order,
                    'desc' => (int)$this->options['desc'],
                    'page' => $this->options['page']
                );
            
                if($this->options['order'] == $order) {
                    $params['desc'] = (int)(!$this->options['desc']);
                }
                $url = $this->urlGetParams(null, $params);
            ?>
            <th>
                <a href="<?php echo $url; ?>">
                    <?php echo $this->translate('order_' . $order) ?> <?php if($order == $this->options['order']):?><i class="<?php if($this->options['desc']): ?>icon-caret-down<?php else: ?>icon-caret-up<?php endif; ?>"></i><?php endif; ?>
                </a>
            </th>
            <?php endforeach; ?>
            <th></th>
        </tr>
        <?php if(count($this->distributors) == 0): ?>
        <tr>
            <td colspan="<?php echo count($this->options['orders']) + 2 ?>" class="table-nothing"><?php echo $this->translate('Nie dodano żadnych dystrybutorów') ?></td>
        </tr>
        <?php else: ?>
        <?php foreach($this->distributors as $distributor): ?>
        <tr>
            <td class="table_nr"><?php echo ++$nr ?></td>   
            <?php foreach($this->options['orders'] as $order): ?>
            <?php if($order == 'distributor_name'): ?>
            <td><?php echo $distributor->getName() ?></td>
            <?php endif ?>
            <?php endforeach ?>
            <td class="table-options">
                <a href="<?php echo $this->baseUrl('/beermanufacturer/index/id/' . $distributor->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Lista wytwórców') ?>"><i class="icon-list"></i></a>
                <a href="<?php echo $this->baseUrl('/beerdistributor/edit/id/' . $distributor->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->baseUrl('/beerdistributor/delete/id/' . $distributor->getId()) ?>" class="btn btn-confirm btn-danger btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Usuń') ?>"><i class="icon-trash icon-white"></i></a>
            </td>
  
        </tr>
        <?php endforeach; ?>
        <?php endif ?>
    </table>
    <?php echo $this->paginationControl($this->distributors,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => array(
                                        'items' => $this->items,
                                        'order' => $this->order,
                                        'desc' => (int)($this->desc)
                                    )
                                )); ?>
</fieldset>