<?php 

use PoradnikPiwny\Security,
    PoradnikPiwny\Entities\User;

$title = $this->translate('Lista użytkowników');

$this->headTitle()->append($title); 
$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć tego użytkownika ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a").tooltip() });'
);

$nr = ($this->users->getCurrentPageNumber()-1) * $this->users->getItemCountPerPage();
?>
<?php echo $this->render('confirm.phtml') ?>
<fieldset class="table_container">
    <legend>
        <?php echo $title ?>
        <span id="options_container">
            <a href="#" id="b_options_container"><i class="icon-caret-right"></i> <?php echo $this->translate('Opcje') ?></a>
        </span>
    </legend>
    <?php echo $this->render('paginator_options.phtml') ?>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th>#</th>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php 
                $params = array(
                    'items' => $this->options['items'],
                    'order' => $order,
                    'desc' => (int)$this->options['desc'],
                    'page' => $this->options['page']
                );
            
                if($this->options['order'] == $order) {
                    $params['desc'] = (int)(!$this->options['desc']);
                }
                $url = $this->urlGetParams(null, $params);
            ?>
            <th>
                <a href="<?php echo $url; ?>">
                    <?php echo $this->translate('order_' . $order) ?> <?php if($order == $this->options['order']):?><i class="<?php if($this->options['desc']): ?>icon-caret-down<?php else: ?>icon-caret-up<?php endif; ?>"></i><?php endif; ?>
                </a>
            </th>
            <?php endforeach; ?>
            <th></th>
        </tr>
        <?php foreach($this->users as $user): ?>
        <?php
            $self = false;
            $owner = false;
            if($user->getId() == $this->user->getId()) {
                $self = true;
            } elseif($this->rAcl->isChildRoleForUser($user->getRole(), $this->user)) {
                $owner = true;
            }
        ?>
        <tr>
            <td class="table_nr"><?php echo ++$nr ?></td>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php if($order == 'user_visiblename'): ?>
            <td>
                <?php if($owner): ?>
                    <a href="<?php echo $this->baseUrl('/users/info/id/' . $user->getId()) ?>"><?php echo $user->getVisibleName() ?></a> 
                <?php else: ?>
                    <?php echo $user->getVisibleName() ?>
                <?php endif ?>
            </td>
            <?php elseif($order == 'role_name'): ?>
            <?php $roleId = $user->getRole()->getId() ?>
            <td>
                <?php
                switch($roleId) {
                    case Security::ROLE_USER:
                        echo $this->translate('Użytkownik');
                        break;
                    case Security::ROLE_PIWOSZ:
                        echo $this->translate('Piwosz');
                        break;
                    case Security::ROLE_TESTER:
                        echo $this->translate('Tester');
                        break;
                    case Security::ROLE_ADMIN:
                        echo $this->translate('Administrator');
                        break;
                    case Security::ROLE_PROGRAMMER:
                        echo $this->translate('Programista');
                        break;
                }
                ?>
            </td>
            <?php elseif($order == 'user_status'): ?>
            <?php $status = $user->getStatus(); ?>
            <td>
                <?php
                switch($status) {
                    case User::STATUS_ACTIVE:
                        echo $this->translate('Aktywny');
                        break;
                    case User::STATUS_INACTIVE:
                        echo $this->translate('Nieaktywny');
                        break;
                    case User::STATUS_BANNED:
                        echo $this->translate('Zbanowany');
                        break;
                }
                ?>
            </td>
            <?php endif ?>
            <?php endforeach ?>
            <td class="table-options">
            <?php if($self): ?>
                <a href="<?php echo $this->baseUrl('/account/settings') ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->baseUrl('/account/changepass') ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Zmień hasło') ?>"><i class="icon-lock"></i></a>
            <?php elseif($owner): ?>
                <a href="<?php echo $this->baseUrl('/users/edit/id/' . $user->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->baseUrl('/users/changepass/id/' . $user->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Zmień hasło') ?>"><i class="icon-lock"></i></a>
                <a href="<?php echo $this->baseUrl('/users/delete/id/' . $user->getId()) ?>" class="btn btn-confirm btn-danger btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Usuń') ?>"><i class="icon-trash icon-white"></i></a>
            <?php endif ?>  
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginationControl($this->users,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => array(
                                        'items' => $this->items,
                                        'order' => $this->order,
                                        'desc' => (int)($this->desc)
                                    )
                                )); ?>
</fieldset>