<?php

use PoradnikPiwny\Security;

$this->headTitle()->append($this->translate('Panel administratora')); 
?>
<fieldset class="form_container">
    <legend><?php echo $this->translate('Informacje ogólne') ?></legend>
    <table class="table table-striped table-hover">
        <tr>
            <th colspan="2"><?php echo $this->translate('System') ?></th>
        </tr>
        <tr>
            <td width="250"><?php echo $this->translate('PHP:') ?></td>
            <?php
                $version = phpversion();
                $pos = strpos(phpversion(), '-');
                if($pos != 0) $version = substr($version, 0, $pos);
            ?>
            <td><?php echo $version ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Zend Framework:') ?></td>
            <td><?php echo \Zend_Version::VERSION ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Poradnik Piwny:') ?></td>
            <td>0.3 beta 2</td>
        </tr>
    </table>
    <br />
    <table class="table table-striped table-hover">   
        <tr>
            <th colspan="2"><?php echo $this->translate('Konto') ?></th>
        </tr>
        <tr>
            <td width="250"><?php echo $this->translate('Nazwa użytkownika:') ?></td>
            <td><?php echo $this->user->getUsername() ?></td>
        </tr>
        <tr>
            <td width="250"><?php echo $this->translate('Podpis:') ?></td>
            <td><?php echo $this->user->getVisibleName() ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Email:') ?></td>
            <td><?php echo $this->user->getEmail() ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Rola:') ?></td>
            <?php $roleId = $this->user->getRole()->getId() ?>
            <td>
                <?php
                switch($roleId) {
                    case Security::ROLE_USER:
                        $role = $this->translate('Użytkownik');
                        break;
                    case Security::ROLE_PIWOSZ:
                        $role = $this->translate('Piwosz');
                        break;
                    case Security::ROLE_TESTER:
                        $role = $this->translate('Tester');
                        break;
                    case Security::ROLE_ADMIN:
                        $role = $this->translate('Administrator');
                        break;
                    case Security::ROLE_PROGRAMMER:
                        $role = $this->translate('Programista');
                        break;
                }
                echo $role;
                ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Imię:') ?></td>
            <td><?php echo (!empty($this->userMeta['name'])) ? $this->userMeta['name'] : '-' ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Nazwisko:') ?></td>
            <td><?php echo (!empty($this->userMeta['name'])) ? $this->userMeta['surname'] : '-' ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Motyw graficzny:') ?></td>
            <td><?php echo $this->themes[(isset($this->userMeta['theme'])) ? $this->userMeta['theme'] : 'bootstrap'] ?></td>
        </tr>
    </table>
</fieldset>