<?php

use WS\Tool;

$this->headTitle()->append($this->translate('Wyszukiwanie piwa'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/pp_observer.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/beer_get_distributors.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/beer_get_regions_cities.js'));

?>
<fieldset class="form_container">
    <legend><?php echo $this->translate('Wyszukiwanie piwa') ?></legend>
    <?php echo $this->form ?>
</fieldset>