<?php 

use WS\Tool;

$title = $this->translate('Edytowanie potomka');
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/beerfamily_add.js'));
$this->headTitle()->append($title); 

$this->headScript()->appendScript(
    'var MSG_DELETE = "' . $this->translate('Usuń') . '"'
);
?>
<fieldset class="form_container">
    <legend><?php echo $title ?></legend>
    <?php echo $this->form ?>
</fieldset>