<?php 

use WS\Tool;

$this->headTitle()->append($this->translate('Dodawanie nowego wytwórcy'));

$urlMaps = 'https://maps.googleapis.com/maps/api/js?key=' . $this->apiKey . '&sensor=false';

$this->headScript()->appendFile($urlMaps);
$this->headScript()->appendFile(Tool::getStaticUrl('js/pp_observer.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/pp_multilang_field.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/beer_get_regions_cities.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/beermanufacturer_add.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/wysihtml5-0.3.0.min.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/bootstrap-wysihtml5.js'));
$this->headScript()->appendFile(Tool::getStaticUrl('js/_admin/locales/bootstrap-wysihtml5.' . PP_LANG . '.js'));

$this->headLink()->appendStylesheet(Tool::getStaticUrl('css/_admin/bootstrap-wysihtml5.css'));

$this->headScript()->appendScript('
    $(function() {
        $(".multilang-textarea").pp_multilang_field("beermanufacturer-description");
        $(".multilang-textarea").wysihtml5({
            "font-styles": false,
            "image": false,
            "stylesheets": ["' . Tool::getStaticUrl('css/_admin/wysiwyg-color.css') . '"],
            "locale": "' . PP_LANG . '"
        });
    }); 
');

?>

<fieldset class="form_container">
    <legend><?php echo $this->translate('Dodawanie nowego wytwórcy') ?></legend>
    <?php echo $this->form ?>
</fieldset>