<?php 

$title = $this->translate('Lista walut');
$this->headTitle()->append($title); 
$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć tą walutę ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a").tooltip() });'
);

$nr = ($this->currencies->getCurrentPageNumber()-1) * $this->currencies->getItemCountPerPage();
?>
<?php echo $this->render('confirm.phtml') ?>
<fieldset class="table_container">
    <legend>
        <?php echo $title ?>
        <span id="options_container">
            <a href="#" id="b_options_container"><i class="icon-caret-right"></i> <?php echo $this->translate('Opcje') ?></a>
        </span>
    </legend>
    <?php echo $this->render('paginator_options.phtml') ?>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th>#</th>
            <?php foreach($this->options['orders'] as $order): ?>
            <?php 
                $params = array(
                    'items' => $this->options['items'],
                    'order' => $order,
                    'desc' => (int)$this->options['desc'],
                    'page' => $this->options['page']
                );
            
                if($this->options['order'] == $order) {
                    $params['desc'] = (int)(!$this->options['desc']);
                }
                $url = $this->urlGetParams(null, $params);
            ?>
            <th>
                <a href="<?php echo $url; ?>">
                    <?php echo $this->translate('order_' . $order) ?> <?php if($order == $this->options['order']):?><i class="<?php if($this->options['desc']): ?>icon-caret-down<?php else: ?>icon-caret-up<?php endif; ?>"></i><?php endif; ?>
                </a>
            </th>
            <?php endforeach; ?>
            <th></th>
        </tr>
        <?php if(count($this->currencies) == 0): ?>
        <tr>
            <td colspan="<?php echo count($this->options['orders']) + 2 ?>" class="table-nothing"><?php echo $this->translate('Nie dodano żadnych walut') ?></td>
        </tr>
        <?php else: ?>
            <?php  foreach($this->currencies as $currency): ?>
            <tr>
                <td class="table_nr"><?php echo ++$nr ?></td>
                <?php foreach($this->options['orders'] as $order): ?>
                <?php if($order == 'currency_name'): ?>
                <td><?php echo $currency->getName() ?></td> 
                <?php elseif($order == 'currency_shortcut'): ?>
                <td><?php echo $currency->getShortcut() ?></td>
                <?php elseif($order == 'currency_symbol'): ?>
                <td><?php echo $currency->getSymbol() ?></td>
                <?php endif ?>
                <?php endforeach ?>
                <td class="table-options">
                    <a href="<?php echo $this->baseUrl('/currencyexchange/index/id/' . $currency->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Przelicznik') ?>"><i class="icon-exchange"></i></a>
                    <a href="<?php echo $this->baseUrl('/currency/edit/id/' . $currency->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj')?>"><i class="icon-edit"></i></a>
                    <a href="<?php echo $this->baseUrl('/currency/delete/id/' . $currency->getId()) ?>" class="btn btn-confirm btn-danger btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Usuń')?>"><i class="icon-trash icon-white"></i></a>
                </td>        
            </tr>
            <?php endforeach; ?>
        <?php endif ?>
    </table>
    <?php echo $this->paginationControl($this->currencies,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => array(
                                        'items' => $this->items,
                                        'order' => $this->order,
                                        'desc' => (int)($this->desc)
                                    )
                                )); ?>
</fieldset>