<?php 

$title = sprintf($this->translate('Lista przeliczników dla waluty "%s"'), $this->currency->getName());
$this->headTitle()->append($title); 
$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć dany przelicznik ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a").tooltip() });'
);

$fields = array(
    'Nazwa waluty' => 'name',
    'Mnożnik' => 'multiplier',
    'Ostatnia modyfikacja' => 'lastUpdated'
);

$nr = ($this->exchanges->getCurrentPageNumber()-1) * $this->exchanges->getItemCountPerPage();

?>
<fieldset class="table_container">
    <legend><?php echo $title ?></legend>
    
    <form class="form form-inline table-filters" method="GET">
        <input type="submit" class="btn btn-primary" value="<?php echo $this->translate('Pokaż') ?>" />  
        <select name="items" onChange="this.form.submit()">
            <?php foreach(array(10,20,50,100) as $count): ?>
            <option value="<?php echo $count ?>"<?php if($count == $this->items): ?> selected="selected"<?php endif ?>><?php echo $count ?></option>
            <?php endforeach ?>
        </select>
        <label><?php echo $this->translate('rekordów') ?></label>
    </form>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th><?php echo $this->translate('Nr') ?></th>
            <?php foreach($fields as $name => $field): ?>
            <?php 
                if($this->order == $field) {
                    $url = $this->urlGetParams(null, array(
                                'items' => $this->items,
                                'order' => $this->order,
                                'desc' => (int)(!$this->desc),
                                'page' => $this->page
                            ));
                } else {
                    $url = $this->urlGetParams(null, array(
                                'order' => $field,
                                'items' => $this->items,
                                'page' => $this->page
                            ));
                }
            ?>
            <th>
                <a href="<?php echo $url ?>">
                    <?php echo $this->translate($name) ?> <?php if($field == $this->order):?> <?php if($this->desc): ?>&#8744<?php else: ?>&#8743<?php endif ?><?php endif ?>
                </a>
            </th>
            <?php endforeach ?>
            <th></th>
        </tr>
        <?php if(count($this->exchanges) == 0): ?>
        <tr>
            <td colspan="5" class="table-nothing"><?php echo $this->translate('Nie dodano żadnych walut') ?></td>
        </tr>
        <?php else: ?>
            <?php  foreach($this->exchanges as $exchange): ?>
            <tr>
                <td class="table_nr"><?php echo ++$nr ?></td>
                <td><a href="/currencyexchange/index/id/<?php echo $exchange->getCurrency()->getId() ?>"><?php echo $exchange->getCurrency()->getName() ?></a></td>
                <?php $m = $exchange->getMultiplier() ?>
                <?php if($m == null): ?>
                <td> - </td>
                <?php else: ?>
                <td><?php echo $m ?></td>
                <?php endif ?>
                <?php $d = $exchange->getLastUpdated() ?>
                <?php if($d == null): ?>
                <td> - </td>
                <?php else: ?>
                <td><?php echo $d ?></td>
                <?php endif ?>
                <td class="table-options">
                    <a href="<?php echo $this->baseUrl('/currencyexchange/edit/id/' . $exchange->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit"></i></a>
                </td>        
            </tr>
            <?php endforeach; ?>
        <?php endif ?>
    </table>
    <?php echo $this->paginationControl($this->exchanges,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => array(
                                        'items' => $this->items,
                                        'order' => $this->order,
                                        'desc' => (int)($this->desc)
                                    )
                                )); ?>
</fieldset>