<?php 

use WS\Tool,
    PoradnikPiwny\Entities\BeerImage;

$title = $this->translate('Galeria piwa');

$this->headTitle()->append($title);
$this->headScript()->appendScript(
    'var MSG_DANGER_BTN = "' . $this->translate('Czy na pewno chcesz usunąć dane zdjęcie ?') . '"' . PHP_EOL . 
    '$(function() {$(".table-options a, .btn-main-image").tooltip() });'
);

$m_image = $this->beer->getImage();
$m_imageId = -1;
if($m_image != null)
{
    $m_imageId = $m_image->getId();
}

$nr = ($this->images->getCurrentPageNumber()-1) * $this->images->getItemCountPerPage();

$this->isEnablePaginatorOrders = false;
$this->isEnablePaginatorOrder = false;
$this->isEnablePaginatorDesc = false;

?>
<?php echo $this->render('confirm.phtml') ?>
<fieldset class="table_container">
    <legend>
        <?php echo $title ?>
        <span id="options_container">
            <a href="#" id="b_options_container"><i class="icon-caret-right"></i> <?php echo $this->translate('Opcje') ?></a>
        </span>
    </legend>
    <?php echo $this->render('paginator_options.phtml') ?>
    
    <table class="table table-striped table-hover table-standard-formed">
        <tr>
            <th><?php echo $this->translate('Nr'); ?></th>
            <th></th>
            <th></th>
        </tr>
        <?php if(count($this->images) == 0): ?>
        <tr>
            <td colspan="3" class="table-nothing"><?php echo $this->translate('Nie dodano żadnych zdjęć') ?></td>
        </tr>
        <?php else: ?>
            <?php foreach($this->images as $image): ?>
            <tr>
                <td class="table_nr"><?php echo ++$nr ?></td>
                <td>
                    <?php 
                    $title = $image->getTitle();
                    if(!empty($title)):
                    ?>
                    <p><?php echo $title ?></p>
                    <?php endif ?>
                    <?php 
                    $path = $image->getPath();
                    if($path != null && !empty($path)):
                    ?>
                    <img src="<?php echo $this->thumb(UPLOAD_PATH .'/images/'. $path, 300, 300, UPLOAD_CACHE_PATH . '/images/' . $image->getId(), Tool::getStaticUrl('/upload/_cache/images/' . $image->getId())) ?>" class="img-polaroid" alt="" />
                    <?php endif ?>
                    <p class="image_dateadded"><?php echo $image->getDateAdded()->toString() ?></p> 
                </td>
                <td class="table-options">
                    <?php if($nr != 1): ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/up/id/' . $image->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Do góry') ?>"><i class="icon-sort-up"></i></a>
                    <?php endif ?>
                    <?php if($this->images->getTotalItemCount() != $nr): ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/down/id/' . $image->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Na dół') ?>"><i class="icon-sort-down"></i></a>
                    <?php endif ?>
                    <?php if($image->getStatus() == BeerImage::STATUS_NIEWIDOCZNY): ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/setvisible/id/' . $image->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Niewidoczne') ?>"><i class="icon-eye-close"></i></a>
                    <?php else: ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/setinvisible/id/' . $image->getId()) ?>" class="btn btn-mini btn-primary" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Widoczne') ?>"><i class="icon-eye-open"></i></a>
                    <?php endif ?>
                    <?php if($m_imageId != $image->getId()): ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/setmain/id/' . $image->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Oznacz jako główne') ?>"><i class="icon-tag"></i></a>
                    <?php else: ?>
                    <button class="btn btn-inverse btn-mini btn-main-image" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Główne') ?>"><i class="icon-white icon-tag"></i></button>                    
                    <?php endif ?>
                    <a href="<?php echo $this->baseUrl('/beerimage/edit/id/' . $image->getId()) ?>" class="btn btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Edytuj') ?>"><i class="icon-edit icon-white"></i></a>
                    <a href="<?php echo $this->baseUrl('/beerimage/delete/id/' . $image->getId()) ?>" class="btn btn-confirm btn-danger btn-mini" data-toggle="tooltip" data-original-title="<?php echo $this->translate('Usuń') ?>"><i class="icon-trash icon-white"></i></a>
            </td>

            </tr>
            <?php endforeach; ?>
        <?php endif ?>
    </table>
    <?php 
        $pagParams = array(
            'items' => $this->items,
            'order' => $this->order,
            'desc' => (int)($this->desc)
        );

        echo $this->paginationControl($this->images,
                                'Sliding',
                                'paginator.phtml', 
                                array(
                                    'params' => $pagParams
                                ));   
    ?>
</fieldset>